services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb-container
    restart: unless-stopped
    ports:
      - "27017:27017"
    # volumes:
    #   - mongo_data:/data/db

  redis:
    image: redis:7
    container_name: redis-container
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --save 900 1 --save 300 10 --save 60 10000
    # volumes:
    #   - redis_data:/data
