services:
  redis:
    image: redis:7
    container_name: redis-container
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --save 900 1 --save 300 10 --save 60 10000
    # volumes:
    #   - redis_data:/data  # 데이터 영속성을 위한 볼륨 (테스트 환경에서는 주석 처리)

