spring:
  data:
    redis:
      host: localhost
      port: 6379
      username: srpark
      password: admin
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 2

    mongodb:
      uri: mongodb://srpark:admin@localhost:27017/url?authSource=url&minPoolSize=10&maxPoolSize=50&maxIdleTimeMS=30000

base:
  url: http://localhost:8080
